"""investor funding and interest accrual

Revision ID: 0034_investor_funding
Revises: 0033_auth_session_security
Create Date: 2026-07-16
"""
from alembic import op
import sqlalchemy as sa

revision = "0034_investor_funding"
down_revision = "0033_auth_session_security"
branch_labels = None
depends_on = None


def has_table(name):
    return op.get_bind().dialect.has_table(op.get_bind(), name)

def upgrade():
    if not has_table("investors"):
        op.create_table("investors",
            sa.Column("id", sa.Integer(), primary_key=True), sa.Column("investor_number", sa.String(32), nullable=False), sa.Column("investor_type", sa.String(20), nullable=False, server_default="INDIVIDUAL"), sa.Column("full_name", sa.String(150), nullable=False), sa.Column("company_name", sa.String(150)), sa.Column("nic", sa.String(50)), sa.Column("company_registration_number", sa.String(80)), sa.Column("tax_identification_number", sa.String(80)), sa.Column("mobile", sa.String(30)), sa.Column("email", sa.String(120)), sa.Column("address", sa.Text()), sa.Column("bank_name", sa.String(120)), sa.Column("bank_branch", sa.String(120)), sa.Column("bank_account_name", sa.String(150)), sa.Column("bank_account_number", sa.String(80)), sa.Column("status", sa.String(20), nullable=False, server_default="ACTIVE"), sa.Column("notes", sa.Text()), sa.Column("created_by", sa.Integer(), sa.ForeignKey("users.id")), sa.Column("created_at", sa.DateTime(), nullable=False, server_default=sa.func.now()), sa.Column("updated_at", sa.DateTime(), nullable=False, server_default=sa.func.now()), sa.Column("deactivated_at", sa.DateTime()), sa.UniqueConstraint("investor_number", name="uq_investor_number"))
        op.create_index("ix_investors_investor_number", "investors", ["investor_number"]); op.create_index("ix_investors_status", "investors", ["status"])
    if not has_table("investor_funding_agreements"):
        op.create_table("investor_funding_agreements",
            sa.Column("id", sa.Integer(), primary_key=True), sa.Column("agreement_number", sa.String(40), nullable=False), sa.Column("investor_id", sa.Integer(), sa.ForeignKey("investors.id"), nullable=False), sa.Column("agreement_name", sa.String(150)), sa.Column("agreement_date", sa.Date(), nullable=False), sa.Column("start_date", sa.Date(), nullable=False), sa.Column("maturity_date", sa.Date()), sa.Column("currency", sa.String(3), nullable=False, server_default="LKR"), sa.Column("original_principal_amount", sa.Numeric(18,2), nullable=False, server_default="0"), sa.Column("current_principal_balance", sa.Numeric(18,2), nullable=False, server_default="0"), sa.Column("interest_rate", sa.Numeric(10,4), nullable=False, server_default="0"), sa.Column("interest_rate_period", sa.String(20), nullable=False, server_default="MONTHLY"), sa.Column("calculation_method", sa.String(40), nullable=False, server_default="MONTHLY_AVERAGE_DAILY_BALANCE"), sa.Column("interest_payment_frequency", sa.String(20), nullable=False, server_default="MONTHLY"), sa.Column("compounding_method", sa.String(30), nullable=False, server_default="SIMPLE"), sa.Column("day_count_basis", sa.String(20), nullable=False, server_default="ACTUAL"), sa.Column("interest_payment_method", sa.String(30), nullable=False, server_default="BANK_TRANSFER"), sa.Column("funding_account_id", sa.Integer(), sa.ForeignKey("accounting_accounts.id")), sa.Column("investor_liability_account_id", sa.Integer(), sa.ForeignKey("accounting_accounts.id"), nullable=False), sa.Column("interest_expense_account_id", sa.Integer(), sa.ForeignKey("accounting_accounts.id"), nullable=False), sa.Column("accrued_interest_payable_account_id", sa.Integer(), sa.ForeignKey("accounting_accounts.id"), nullable=False), sa.Column("withholding_tax_account_id", sa.Integer(), sa.ForeignKey("accounting_accounts.id")), sa.Column("withholding_tax_rate", sa.Numeric(10,4)), sa.Column("allow_additional_funding", sa.Boolean(), nullable=False, server_default=sa.true()), sa.Column("allow_partial_withdrawal", sa.Boolean(), nullable=False, server_default=sa.true()), sa.Column("auto_accrual_enabled", sa.Boolean(), nullable=False, server_default=sa.true()), sa.Column("auto_capitalize_interest", sa.Boolean(), nullable=False, server_default=sa.false()), sa.Column("status", sa.String(20), nullable=False, server_default="DRAFT"), sa.Column("closed_at", sa.DateTime()), sa.Column("created_by", sa.Integer(), sa.ForeignKey("users.id")), sa.Column("created_at", sa.DateTime(), nullable=False, server_default=sa.func.now()), sa.Column("updated_at", sa.DateTime(), nullable=False, server_default=sa.func.now()), sa.UniqueConstraint("agreement_number", name="uq_investor_funding_agreement_number"))
        for c in ["agreement_number","investor_id","status"]: op.create_index(f"ix_investor_funding_agreements_{c}", "investor_funding_agreements", [c])
    if not has_table("investor_funding_transactions"):
        op.create_table("investor_funding_transactions",
            sa.Column("id", sa.Integer(), primary_key=True), sa.Column("transaction_number", sa.String(40), nullable=False), sa.Column("investor_id", sa.Integer(), sa.ForeignKey("investors.id"), nullable=False), sa.Column("agreement_id", sa.Integer(), sa.ForeignKey("investor_funding_agreements.id"), nullable=False), sa.Column("transaction_type", sa.String(30), nullable=False), sa.Column("transaction_date", sa.Date(), nullable=False), sa.Column("accounting_date", sa.Date(), nullable=False), sa.Column("amount", sa.Numeric(18,2), nullable=False), sa.Column("bank_account_id", sa.Integer(), sa.ForeignKey("accounting_accounts.id")), sa.Column("reference", sa.String(120)), sa.Column("remarks", sa.Text()), sa.Column("journal_entry_id", sa.Integer(), sa.ForeignKey("accounting_journal_entries.id")), sa.Column("status", sa.String(20), nullable=False, server_default="DRAFT"), sa.Column("reversal_of_transaction_id", sa.Integer(), sa.ForeignKey("investor_funding_transactions.id")), sa.Column("reversed_at", sa.DateTime()), sa.Column("reversal_reason", sa.Text()), sa.Column("created_by", sa.Integer(), sa.ForeignKey("users.id")), sa.Column("created_at", sa.DateTime(), nullable=False, server_default=sa.func.now()), sa.UniqueConstraint("transaction_number", name="uq_investor_funding_transaction_number"))
        for c in ["transaction_number","investor_id","agreement_id","transaction_date","accounting_date","status"]: op.create_index(f"ix_investor_funding_transactions_{c}", "investor_funding_transactions", [c])
    if not has_table("investor_interest_accruals"):
        op.create_table("investor_interest_accruals",
            sa.Column("id", sa.Integer(), primary_key=True), sa.Column("investor_id", sa.Integer(), sa.ForeignKey("investors.id"), nullable=False), sa.Column("agreement_id", sa.Integer(), sa.ForeignKey("investor_funding_agreements.id"), nullable=False), sa.Column("accrual_period_start", sa.Date(), nullable=False), sa.Column("accrual_period_end", sa.Date(), nullable=False), sa.Column("days_in_period", sa.Integer(), nullable=False), sa.Column("opening_principal_balance", sa.Numeric(18,2), nullable=False), sa.Column("closing_principal_balance", sa.Numeric(18,2), nullable=False), sa.Column("average_daily_balance", sa.Numeric(18,2), nullable=False), sa.Column("interest_rate", sa.Numeric(10,4), nullable=False), sa.Column("interest_rate_period", sa.String(20), nullable=False), sa.Column("calculation_method", sa.String(40), nullable=False), sa.Column("gross_interest_amount", sa.Numeric(18,2), nullable=False), sa.Column("withholding_tax_amount", sa.Numeric(18,2), nullable=False, server_default="0"), sa.Column("net_interest_payable", sa.Numeric(18,2), nullable=False), sa.Column("capitalization_amount", sa.Numeric(18,2), nullable=False, server_default="0"), sa.Column("payment_amount", sa.Numeric(18,2), nullable=False, server_default="0"), sa.Column("status", sa.String(20), nullable=False, server_default="CALCULATED"), sa.Column("journal_entry_id", sa.Integer(), sa.ForeignKey("accounting_journal_entries.id")), sa.Column("payment_journal_entry_id", sa.Integer(), sa.ForeignKey("accounting_journal_entries.id")), sa.Column("capitalization_journal_entry_id", sa.Integer(), sa.ForeignKey("accounting_journal_entries.id")), sa.Column("posted_at", sa.DateTime()), sa.Column("reversed_at", sa.DateTime()), sa.Column("reversal_journal_id", sa.Integer(), sa.ForeignKey("accounting_journal_entries.id")), sa.Column("created_by", sa.Integer(), sa.ForeignKey("users.id")), sa.Column("created_at", sa.DateTime(), nullable=False, server_default=sa.func.now()), sa.Column("updated_at", sa.DateTime(), nullable=False, server_default=sa.func.now()), sa.UniqueConstraint("agreement_id", "accrual_period_start", "accrual_period_end", name="uq_investor_interest_period"))
        for c in ["investor_id","agreement_id","accrual_period_end","status"]: op.create_index(f"ix_investor_interest_accruals_{c}", "investor_interest_accruals", [c])

def downgrade():
    for t in ["investor_interest_accruals","investor_funding_transactions","investor_funding_agreements","investors"]:
        if has_table(t): op.drop_table(t)
